version: "3.8"

services:
  node-demo:
    container_name: node-demo
    image: node-demo:1.0.0
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3200:3200"
    environment:
      APPID: 1000
      NAME: ${NAME}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
